### ISSUE TITLE
Installing on HDP 2.4

### ISSUE THREAD

**Issue by Reedler** [Symantec/ambari-elasticsearch-service#1]
Error when installing with ambari 2.2.2.0 HDP 2.4
File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 291, in _call
    raise Fail(err_msg)
resource_management.core.exceptions.Fail: Execution of '/usr/bin/yum -d 0 -e 0 -y install elasticsearch-1.7.1' returned 1. Error: Nothing to do

**Comment by ambud** [comment]
2 pre-checks:
1. Is elasticsearch already installed on that machine?
2. Is elasticsearch-1.7.1 package available in the yum repo?

**Comment by Reedler** [comment]
That got it! I had the repo for 2.x installed. Thanks man! Any word on an
ambari install with the latest version of elastic search?

_Aaron Reed_

_Systems Engineer42Six Solutions, a CSRA Company_

_Office: 410-872-2299_
_areed@42six.com areed@42six.com_

**Comment by ambud** [comment]
We will look into upgrading the stack code to use 2.x.

Closing this issue.
